version: '3.8'

# Support auto reload for development.
#
# Run `docker-compose -f docker-compose.prod.yml up` for production.
services:
  backend:
    container_name: dm_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
  frontend:
    container_name: dm_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend/src:/app/src
  db:
    container_name: dm_db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres_data:

