FROM python:slim

RUN apt-get update && apt-get install -y build-essential python3-dev git libpq-dev netcat

ENV FLASK_APP "app.py"
ENV FLASK_ENV "development"

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /app
WORKDIR /app

ENV PYTHONPATH=/app

#RUN chmod +x backend/entrypoint.sh

EXPOSE 5000

#ENTRYPOINT ["./entrypoint.sh"]
CMD flask run --host 0.0.0.0
