#########
# BUILD #
#########

# pull official base image
FROM python:slim as builder

RUN apt-get update && apt-get install -y build-essential python3-dev libpq-dev
RUN mkdir /install

COPY requirements.txt /requirements.txt
RUN pip install --prefix=/install --no-warn-script-location -r /requirements.txt


#########
# FINAL #
#########

# pull official base image
FROM python:slim

# reinstall libpq because psycopg2 relies on the libpq library at runtime
RUN apt-get update && \
    apt-get install --no-install-recommends -y libpq5

# copy virtual environment from BUILDER with all installed packages
COPY --from=builder /install /usr/local

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP "server.py"
ENV FLASK_ENV "development"

COPY . /app
WORKDIR /app

CMD flask run --host 0.0.0.0
