FROM python:slim

RUN apt-get update && apt-get install -y build-essential python3-dev libpq-dev netcat

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP "server.py"
ENV FLASK_ENV "development"

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . /app
WORKDIR /app

ENV PYTHONPATH=/app

CMD flask run --host 0.0.0.0
